function params = PAS_Stimulation_DAQ_default_params(varargin)

    default_params = struct(...
        'animal_name'          , 'jan-01-01',...
        'inter_stim_interval'  , [0.05 0.1],...
        'emg_window_output'    , 0.5,...
        'emg_queue_output'     , 0.5,...
        'time_before_stim'     , 500,...
        'time_after_stim'      , 1500,...
        'nb_pulses'            , 12,...
        'fsampling'            , 2000,...
        'refresh_ratio'        , 200,...
        'duration_max'         , 3600,...
        ); % Ajouter des paramètres au fur et à mesure

    if nargin
        params = varargin{1};
        %some parameters are provided as argument, fill the rest:
        all_param_names = fieldnames(default_params);
        for i=1:numel(all_param_names)
            if ~isfield(params,all_param_names(i))
                params.(all_param_names{i}) = default_params.(all_param_names{i});
            end
        end
    else
        params = default_params;
    end
    